version: "3.8"
services:
  backend:
    image: bmcglauser/bookmooch-backend
    ports:
      - '4000:4000'
    environment:
      JWT_SECRET: 'a'

  frontend:
    image: bmcglauser/bookmooch-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
      